#!/bin/bash
# Configure Pulp Keycloak social-auth for local development.
set -euo pipefail

KEYCLOAK_HOST="${KEYCLOAK_HOST:-pulp-ui-2-keycloak}"
KEYCLOAK_REALM="${KEYCLOAK_REALM:-pulp}"
KEYCLOAK_PULP_CLIENT_ID="${KEYCLOAK_PULP_CLIENT_ID:-pulp}"
KEYCLOAK_PULP_CLIENT_SECRET="${KEYCLOAK_PULP_CLIENT_SECRET:-dev-pulp-secret}"
SETTINGS_FILE="/etc/pulp/settings-keycloak.py"

echo "keycloak profile: installing python-social-auth packages..."
uv pip install social-auth-core social-auth-app-Django

echo "keycloak profile: waiting for Keycloak realm ${KEYCLOAK_REALM}..."
until curl -fsS "http://${KEYCLOAK_HOST}:8080/realms/${KEYCLOAK_REALM}" >/dev/null 2>&1; do
  sleep 2
done

PUBLIC_KEY="$(
  curl -fsS "http://${KEYCLOAK_HOST}:8080/realms/${KEYCLOAK_REALM}" \
    | python3 -c 'import json,sys; print(json.load(sys.stdin)["public_key"])'
)"

cat > "${SETTINGS_FILE}" <<EOF
# Generated by pulp-ui-2 keycloak oci-env profile init.sh
#
# These settings are loaded by Pulp via dynaconf (PULP_SETTINGS). Lists must be
# *merged* with Pulp's base settings, not replaced -- assigning a bare list
# would wipe out Django/Pulp's own apps and auth backends. The trailing
# "dynaconf_merge" marker tells dynaconf to append to the existing list.

INSTALLED_APPS = ["social_django", "dynaconf_merge"]

AUTHENTICATION_BACKENDS = [
    "social_core.backends.keycloak.KeycloakOAuth2",
    "dynaconf_merge",
]

SOCIAL_AUTH_PIPELINE = (
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.social_user",
    "social_core.pipeline.user.get_username",
    "social_core.pipeline.social_auth.associate_by_email",
    "social_core.pipeline.user.create_user",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
    "social_core.pipeline.user.user_details",
)

SOCIAL_AUTH_KEYCLOAK_KEY = "${KEYCLOAK_PULP_CLIENT_ID}"
SOCIAL_AUTH_KEYCLOAK_SECRET = "${KEYCLOAK_PULP_CLIENT_SECRET}"
SOCIAL_AUTH_KEYCLOAK_PUBLIC_KEY = "${PUBLIC_KEY}"
SOCIAL_AUTH_KEYCLOAK_AUTHORIZATION_URL = "http://${KEYCLOAK_HOST}:8080/realms/${KEYCLOAK_REALM}/protocol/openid-connect/auth"
SOCIAL_AUTH_KEYCLOAK_ACCESS_TOKEN_URL = "http://${KEYCLOAK_HOST}:8080/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token"
EOF

chmod 644 "${SETTINGS_FILE}"
echo "keycloak profile: wrote ${SETTINGS_FILE}"
